### ISSUE TITLE
Add lookup for trusted keys

### ISSUE THREAD

**Issue by abalmos** [OADA/oada-lookup-js#2]
- [ ] Look up trusted lists of keys and jwks_uri's
- [ ] Follow jwks_uri for intrested key
- [ ] Cache layer for (all?) lookups

**Comment by awlayton** [comment]
This was broken out to [OADA/oada-trusted-jws-js](https://github.com/OADA/oada-trusted-jws-js) correct?

**Comment by abalmos** [comment]
Your right, closing.
